name: Local Test Workflow

on:
  workflow_dispatch: {}

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t test --build-arg HOST=${{ env.HOST }} --build-arg PORT=${{ env.PORT }} .

      - name: Run Docker container
        run: |
          docker run -d -p ${{ env.PORT }}:${{ env.PORT }} --name test-container test

      - name: Test the application
        run: |
          # Wait for the application to be ready
          echo "Waiting for application to start..."
          timeout=30
          while [ $timeout -gt 0 ]; do
            if docker exec test-container ps aux | grep -q "[p]ython"; then
              echo "Application process is running"
              break
            fi
            echo "Application not ready yet, waiting..."
            sleep 2
            timeout=$((timeout - 2))
          done
          
          # Additional wait to ensure app is fully initialized
          sleep 5
          
          # Test that the application is running
          echo "Testing application..."
          curl -f http://localhost:${{ env.PORT }}/ || {
            echo "Curl failed, checking container status:"
            docker logs test-container
            exit 1
          }
          
      - name: Cleanup
        if: always()
        run: |
          docker stop test-container || true
          docker rm test-container || true
